name: Run

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - run: |
          ${{ github.event.inputs.command }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
